# Site settings
title: My Blog
subtitle: "Journal of Brian"
email: iswear@outlook.com
description: "Young & simple, sometimes naive."
baseurl: ""
url: "http://leciel.cc"
twitter_username: "briantsao"
github_username:  "estimation"
instagram_username: "briantsao"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed